name: The Generalist
favicon: null
layout_spectrum: 0.1028229531366378
typography_spectrum: 0.7359140415210277
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.14542739023454487
  lightness: 0.39650559960864484
  saturation: 0.27835695585235953
  rhythmicContrast: 0.4152793688699603
purpose: []
